version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true            # Enabling security
      - xpack.security.transport.ssl.enabled=true  # Enabling SSL for node-to-node communication
      - ELASTIC_PASSWORD=JyzOSl9yte-f7PgXTk+v             # Setting the default 'elastic' user password
      - xpack.security.http.ssl.enabled=false  # Disable HTTP SSL (adjust as needed)
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9201:9200"  # HTTP port (exposed for external access)
      - "9300:9300"  # Transport port (used internally)
volumes:
  esdata:
    driver: local
